w/lecture03/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("test", views.test, name="test"),
    path("<str:name>", views.greet, name="greet"),
]

w/lecture03/lecture03/urls.py
from django.contrib import admin
from django.urls import include, path

import hello.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('timenow/', include("timenow.urls")),
    path("todos/", include("todos.urls"))
]

w/lecture03/timenow/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
]

w/lecture03/todos/urls.py
from django.urls import path
from . import views

app_name = "todos"  # namespacing so we can use `url 'todos:index'` in a.href
urlpatterns = [
    path("", views.index, name="index"),
    path("add-todo/", views.add_todo, name="add"),
]

w/lecture03/hello/models.py
from django.db import models

# Create your models here.

w/lecture03/timenow/models.py
from django.db import models

# Create your models here.

w/lecture03/todos/models.py
from django.db import models

# Create your models here.

w/lecture03/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, "hello/index.html")

def greet(request, name):
    return render(request,
                  "hello/greet.html",
                  {
                      "name": name.capitalize(),
                  })

def test(request):
    return HttpResponse(f"""
        <html>
        <body>
        <h1>Hello, world!</h1>
        <p>Hello, tester!</p>
        </body>
        </html>
    """)

w/lecture03/timenow/views.py
from django.shortcuts import render
from datetime import datetime


def index(request):
    midnight = datetime.now().hour < 1 and datetime.now().minute < 20
    print(datetime.now().time())
    return render(request,
                  "timenow/index.html",
                  {
                      "date": datetime.now().date(),
                      "time": datetime.now().time(),
                      "midnight": midnight,
                  })

w/lecture03/todos/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


class NewTodoForm(forms.Form):
    title = forms.CharField(label="New todo")
    description = forms.CharField(label="Description")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)




def index(request):
    if "todos" not in request.session:
        request.session["todos"] = []

    return render(request, 'todos/index.html', {
        "todos": request.session["todos"]
    })

def add_todo(request):
    if request.method == "POST":
        form = NewTodoForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            priority = form.cleaned_data["priority"]
            request.session["todos"] += [{
                "title": title, "description": description, "priority": priority
            }]
            return HttpResponseRedirect(reverse('todos:index'))
        else:
            return render(request, 'todos/add-todo.html', {
                "form": form
            })

    return render(request, 'todos/add-todo.html',{
        "form": NewTodoForm()
    })

w/lecture03/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Greet</title>
    </head>
    <body>
        <h1 style="background-color: antiquewhite; color: darkblue">
            Hello, {{ name }}!
        </h1>
    </body>
</html>

w/lecture03/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hello, World</title>
    </head>
    <body>
        <h1 style="background-color: bisque">Hello, World!</h1>
    </body>
</html>

w/lecture03/timenow/templates/timenow/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Time Now</title>
        <link rel="stylesheet" href="{% static 'timenow/styles.css' %}">
    </head>
    <body>
        <p>It is currently {{ date }}</p>
        {% if midnight %}
            <p class="midnight">Spoopy time!!!</p>
        {% else %}
            <p>{{ time }}</p>
        {% endif %}

    </body>
</html>

w/lecture03/todos/templates/todos/add-todo.html
{% extends 'todos/layout.html' %}
{% block body %}
    <h1>Add todo</h1>
    <form method="POST" action="{% url 'todos:add' %}">
        <label>
            {% csrf_token %}
            {{ form }}
        </label>
        <input type="submit" value="Add" >
    </form>
    <a href="{% url 'todos:index' %}">Go back</a>
{% endblock %}

w/lecture03/todos/templates/todos/index.html
{% extends 'todos/layout.html' %}
{% block body %}
<h1>Hello, Todos!</h1>
<table>
    <thead>
    <tr>
        <th>TODO</th>
        <th> Description</th>
        <th> Priority</th>
    </tr>
    </thead>
    <tbody>
    {% for todo in todos %}
        <tr>
            <td>{{ todo.title }}</td>
            <td>{{ todo.description }}</td>
            <td>{{ todo.priority }}</td>
        </tr>
        {% empty %}
        <p>There are no todos todo!</p>
    {% endfor %}
    </tbody>
</table>

<a href="{% url 'todos:add' %}">Add a new Todo</a>
{% endblock %}

w/lecture03/todos/templates/todos/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Todos</title>
        <link rel="stylesheet" href="{% static 'todos/styles.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>